spring.application.name=maker

spring.datasource.url=jdbc:postgresql://localhost:5432/pizzaOOP?compatible=16
spring.datasource.username=postgres
spring.datasource.password=123123

spring.flyway.enabled=false