spring.application.name=maker

spring.datasource.url=jdbc:postgresql://localhost:5432/pizzaOOP?compatible=16
spring.datasource.username=postgres
spring.datasource.password=123123
spring.jackson.serialization.fail-on-empty-beans=false

spring.flyway.enabled=false